### ISSUE TITLE
Error at "Using and Compiling OpenSoC Fabric"

### ISSUE THREAD

**Issue by wtlin1228** [LBL-CoDEx/OpenSoCFabric#2]
Tornado Pattern with variable injection rate
`$ sbt "run --sw true --harnessName OpenSoC_CMesh_NeighborTester_VarInjRate --moduleName OpenSoC_CMesh_Flit --injRate 50"`

Shouldn't it be like below?
`$ sbt "run --sw true --harnessName OpenSoC_CMesh_TornadoTester_VarInjRate--moduleName OpenSoC_CMesh_Flit --injRate 50"`

**Comment by ffard-lbl** [comment]
Thanks for pointing out the typo! It's been fixed.
